name: Deploy to Firebase
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Firebase CLI
        run: npm install -g firebase-tools
          
      - name: Deploy to Firebase Hosting
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="./service-account.json"
          firebase use the-law-shop-457607
          firebase deploy --only hosting:root-tls,hosting:thelawshop,hosting:workspace-tls
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}